### ISSUE TITLE
Extension Suggestions

### ISSUE THREAD

**Issue by 0xJuancito** [theredguild/devcontainer#1]
Hey! Here are some suggestions that you may consider to add to the container, from a Security Researcher perspective:

- [Solidity Metrics](https://marketplace.visualstudio.com/items?itemName=tintinweb.solidity-metrics): Useful for a quick codebase analysis, calculate nSLOC, code complexity, and estimate times for a security review.
- [Mark Files](https://marketplace.visualstudio.com/items?itemName=vquelque.markfiles): Useful to keep track of reviewed files, or files in scope.
- Some alternative Solidity Language extension like the one from [tintinweb](https://marketplace.visualstudio.com/items?itemName=tintinweb.vscode-solidity-language), or the one from [Nomic Foundation](https://marketplace.visualstudio.com/items?itemName=NomicFoundation.hardhat-solidity). I personally experienced CPU issues with the extension by Juan Blanco (although it might be an issue on my side)

**Comment by mattaereal** [comment]
Done!

Nomic's was already added, and Mark Files is redundant with weAudit extension from ToB. Thanks!!
